In [3]:
import numpy as np
X = [[1,2,3],[4,5,6],[7,8,9]]
Y = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
X1 = np.mat(X)
Y1 = np.mat(Y)
print(X1)
print(Y1)
Z = np.matmul(X1,Y1)
print(Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [11]:
print(X1*Y1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
